/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ScheduledCrawl': CronHandler<{ topic: 'ico.list.crawled'; data: { urls: string[]; icoData: { detailUrl: string; projectName: string; tokenSymbol: string; chain: string; category: string; status: string }[]; totalCount: number; originalCount: number; crawledAt: string; traceId: string } }>
    'ProcessSingleProject': EventHandler<{ url: string; basicData?: { projectName?: string; tokenSymbol?: string; chain?: string; category?: string; status?: string }; traceId: string }, { topic: 'project.detail.crawled'; data: { projectData?: { name: string; symbol: string; category: string; chain: string; status: string; team: unknown[]; crawledAt: string; sourceUrl: string }; url: string; error?: string; traceId: string } } | { topic: 'project.detail.failed'; data: { projectData?: { name: string; symbol: string; category: string; chain: string; status: string; team: unknown[]; crawledAt: string; sourceUrl: string }; url: string; error?: string; traceId: string } }>
    'DistributeProjectCrawl': EventHandler<{ urls: string[]; icoData: { detailUrl: string; projectName: string; tokenSymbol: string; chain: string; category: string; status: string }[]; totalCount: number; originalCount: number; crawledAt: string; traceId: string }, { topic: 'project.crawl.requested'; data: { url: string; basicData?: { projectName?: string; tokenSymbol?: string; chain?: string; category?: string; status?: string }; traceId: string } }>
    'CrawlTeamInfo': EventHandler<{ projectUrl: string; projectId?: string }, never>
    'AggregateCrawlResults': EventHandler<{ projectData?: { name: string; symbol: string; category: string; chain: string; status: string; team: unknown[]; crawledAt: string; sourceUrl: string }; url: string; error?: string; traceId: string }, never>
    'TriggerManualCrawl': ApiRouteHandler<{ maxProjects?: number; delay?: number }, ApiResponse<200, { success: boolean; totalUrls: number; message: string }> | ApiResponse<500, { success: boolean; error: string }>, { topic: 'ico.list.crawled'; data: { urls: string[]; icoData: { detailUrl: string; projectName: string; tokenSymbol: string; chain: string; category: string; status: string }[]; totalCount: number; originalCount: number; crawledAt: string; traceId: string } }>
    'TriggerICOCrawl': ApiRouteHandler<{ maxProjects?: number; delay?: number }, ApiResponse<200, { success: boolean; totalUrls: number; message: string }> | ApiResponse<500, { success: boolean; error: string }>, { topic: 'ico.list.crawled'; data: { urls: string[]; icoData: { detailUrl: string; projectName: string; tokenSymbol: string; chain: string; category: string; status: string }[]; totalCount: number; originalCount: number; crawledAt: string; traceId: string } }>
    'CrawlTeamTrigger': ApiRouteHandler<{ projectUrl: string; projectId?: string }, ApiResponse<200, { success: boolean; message: string; projectUrl: string }> | ApiResponse<400, { error: string }>, { topic: 'project.team.crawl'; data: { projectUrl: string; projectId?: string } }>
  }
}