const CRYPTORANK_BASE_URL='https://api.cryptorank.io/v0'
const CRYPTORANK_TEAM_URL=`${CRYPTORANK_BASE_URL}/team/by-coin`
const CRYPTORANK_UPCOMING_ICO_URL=`${CRYPTORANK_BASE_URL}/round/upcoming`
const CRYPTORANK_ICO_URL=`${CRYPTORANK_BASE_URL}/round/past`
const CRYPTORANK_ACTIVE_ICO_URL=`${CRYPTORANK_BASE_URL}/round/active`
const CRYPTORANK_DETAIL_URL=`${CRYPTORANK_BASE_URL}/coins`
export { CRYPTORANK_BASE_URL, CRYPTORANK_TEAM_URL, CRYPTORANK_UPCOMING_ICO_URL, CRYPTORANK_DETAIL_URL, CRYPTORANK_ICO_URL, CRYPTORANK_ACTIVE_ICO_URL }